/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData rain_inv = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData droplet = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData long_arrow_alt_down = IconData(0xf309, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData long_arrow_alt_up = IconData(0xf30c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xf72e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
